# GitHub actions workflow for a simple C project

# some docs:
# https://github.com/actions/starter-workflows/
# https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: python --version
    - run: python src/hello.py
    - run: python src/hellomain.py
    - run: PYTHONPATH=src pytest
    - run: make test
    - run: make run
